---
abstract: "an artificial neural network simulator\r"
author:
  - 'Dan Collins <DCOLLINS@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200006, CPAN::Meta::Converter version 2.110440'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AI-ANN
requires:
  Storable: 0
  perl: 5.014000
version: 0.002
